// action_queue.cpp
// Randall Sport Camera Controller (ATmega328P / Arduino Nano compatible)
//
// Processes the output queue of actions generated by the FSM. Actions are simple commands with optional parameters,

#include "action_queue.h"

#if (CFG_ACTION_QUEUE_SIZE <= 1)
  #error "CFG_ACTION_QUEUE_SIZE must be > 1"
#endif

static volatile uint8_t  s_head = 0;
static volatile uint8_t  s_tail = 0;
static volatile uint16_t s_dropped = 0;

static action_t s_buf[CFG_ACTION_QUEUE_SIZE];

static inline uint8_t next_index(uint8_t idx)
{
    idx++;
    if (idx >= CFG_ACTION_QUEUE_SIZE) idx = 0;
    return idx;
}

static inline bool push_core(const action_t *a)
{
    const uint8_t h = s_head;
    const uint8_t n = next_index(h);

    if (n == s_tail)
    {
        s_dropped++;
        return false;
    }

    s_buf[h] = *a;
    s_head = n;
    return true;
}

void actionq_init(void)
{
#ifdef __AVR__
    ATOMIC_BLOCK(ATOMIC_RESTORESTATE)
    {
        s_head = 0;
        s_tail = 0;
        s_dropped = 0;
    }
#else
    s_head = 0;
    s_tail = 0;
    s_dropped = 0;
#endif
}

void actionq_clear(void)
{
#ifdef __AVR__
    ATOMIC_BLOCK(ATOMIC_RESTORESTATE)
    {
        s_head = 0;
        s_tail = 0;
        s_dropped = 0;
    }
#else
    s_head = 0;
    s_tail = 0;
    s_dropped = 0;
#endif
}

uint16_t actionq_dropped(void)
{
#ifdef __AVR__
    uint16_t v;
    ATOMIC_BLOCK(ATOMIC_RESTORESTATE) { v = s_dropped; }
    return v;
#else
    return s_dropped;
#endif
}

uint8_t actionq_count(void)
{
#ifdef __AVR__
    uint8_t h, t;
    ATOMIC_BLOCK(ATOMIC_RESTORESTATE) { h = s_head; t = s_tail; }
#else
    uint8_t h = s_head, t = s_tail;
#endif

    if (h >= t) return (uint8_t)(h - t);
    return (uint8_t)(CFG_ACTION_QUEUE_SIZE - (t - h));
}

bool actionq_push_isr(const action_t *a)
{
    return push_core(a);
}

bool actionq_push(const action_t *a)
{
#ifdef __AVR__
    bool ok;
    ATOMIC_BLOCK(ATOMIC_RESTORESTATE) { ok = push_core(a); }
    return ok;
#else
    return push_core(a);
#endif
}

bool actionq_pop(action_t *out)
{
#ifdef __AVR__
    bool ok = false;
    ATOMIC_BLOCK(ATOMIC_RESTORESTATE)
    {
        if (s_tail == s_head)
        {
            ok = false;
        }
        else
        {
            const uint8_t t = s_tail;
            *out = s_buf[t];
            s_tail = next_index(t);
            ok = true;
        }
    }
    return ok;
#else
    if (s_tail == s_head) return false;
    const uint8_t t = s_tail;
    *out = s_buf[t];
    s_tail = next_index(t);
    return true;
#endif
}
